// Writes test/BEHAVIOR.md: every Playwright test title, grouped by file and describe.
// The e2e suite is the behaviour spec; this is its table of contents.
// Run: npm run test:catalog
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const out = execFileSync('npx', ['playwright', 'test', '--list', '--reporter=json'], {
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
  stdio: ['ignore', 'pipe', 'inherit'],
});
const report = JSON.parse(out);

const projectsOf = (spec) => [...new Set(spec.tests.map((t) => t.projectName))].join(', ');

// Returns the markdown lines of a suite's specs and nested describes, and the spec count.
function walk(suite, depth) {
  const indent = '  '.repeat(depth);
  const lines = [];
  let count = 0;
  for (const spec of suite.specs ?? []) {
    count += 1;
    lines.push(`${indent}- ${spec.title} _(${projectsOf(spec)})_`);
  }
  for (const child of suite.suites ?? []) {
    const nested = walk(child, depth + 1);
    lines.push(`${indent}- **${child.title}**`, ...nested.lines);
    count += nested.count;
  }
  return { lines, count };
}

const files = report.suites.map((file) => ({ file, ...walk(file, 0) }));
const total = files.reduce((sum, f) => sum + f.count, 0);

const header = [
  '# Behaviour catalog',
  '',
  'Generated by `npm run test:catalog` from `npx playwright test --list`. Do not edit by hand.',
  'New behaviour first appears here as a test title: `<actor> <action> → <result>`.',
  '',
  `${total} tests in ${files.length} files.`,
  '',
];
const body = files.flatMap(({ file, lines }) => [`## ${file.title}`, '', ...lines, '']);

writeFileSync('test/BEHAVIOR.md', [...header, ...body].join('\n'));
console.log(`test/BEHAVIOR.md: ${total} tests in ${files.length} files`);
