// Writes test/BEHAVIOR.md: every Playwright test title, grouped by file and describe.
// The e2e suite is the behaviour spec; this is its table of contents.
// Run: npm run test:catalog
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const out = execFileSync('npx', ['playwright', 'test', '--list', '--reporter=json'], {
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
  stdio: ['ignore', 'pipe', 'inherit'],
});
const report = JSON.parse(out);

const lines = [
  '# Behaviour catalog',
  '',
  'Generated by `npm run test:catalog` from `npx playwright test --list`. Do not edit by hand.',
  'New behaviour first appears here as a test title: `<actor> <action> → <result>`.',
  '',
];
let total = 0;

const projectsOf = (spec) => [...new Set(spec.tests.map((t) => t.projectName))].join(', ');

function walk(suite, depth) {
  for (const spec of suite.specs ?? []) {
    total += 1;
    lines.push(`${'  '.repeat(depth)}- ${spec.title} _(${projectsOf(spec)})_`);
  }
  for (const child of suite.suites ?? []) {
    lines.push(`${'  '.repeat(depth)}- **${child.title}**`);
    walk(child, depth + 1);
  }
}

for (const file of report.suites) {
  lines.push(`## ${file.title}`, '');
  walk(file, 0);
  lines.push('');
}
lines.splice(5, 0, `${total} tests in ${report.suites.length} files.`, '');

writeFileSync('test/BEHAVIOR.md', lines.join('\n'));
console.log(`test/BEHAVIOR.md: ${total} tests in ${report.suites.length} files`);
